name: Test
on:
  [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.9
    - name: Run test
       - run: python -m unittest test.py

